# Generated by Django 5.0.2 on 2024-02-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_rating_stars_basket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date',
        ),
        migrations.AddField(
            model_name='product',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
